name: Build and Push Image

on:
  repository_dispatch:
    types: [trigger-workflow]
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          repository: Yuen-Affiliates/scraper
          token: ${{ secrets.GH_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6.4.1
        with:
          context: scraper
          push: true
          tags: ghcr.io/yuen-affiliates/scraper:latest
