name: Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'

jobs:
  scraper:
    runs-on: ubuntu-latest

    permissions:
      packages: read

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          repository: Yuen-Affiliates/scraper
          token: ${{ secrets.GH_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run docker image
        uses: ./scraper
        with:
          build: false
          category: diapers
