name: Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'

jobs:
  scraper:
    runs-on: ubuntu-latest

    permissions:
      packages: read

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          repository: Yuen-Affiliates/scraper
          token: ${{ secrets.GH_TOKEN }}

      - name: Run docker image
        uses: ./scraper
        with:
          category: diapers
          github_token: ${{ secrets.GITHUB_TOKEN }}
