name: Scraper

on:
  schedule:
    - cron: '0 10 * * *'
    
  workflow_dispatch:
    inputs:
      count:
        description: Count
        required: false
        type: number
      sources:
        description: Sources
        required: false
        type: string
      verbose:
        description: Verbose
        required: false
        type: boolean

jobs:
  scraper:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          repository: Yuen-Affiliates/scraper
          token: ${{ secrets.GH_TOKEN }}

      - name: Run docker image
        uses: ./scraper
        with:
          category: diapers
          count: ${{ inputs.count }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          sources: ${{ inputs.sources }}
          verbose: ${{ inputs.verbose }}
