name: Scraper

on:
  schedule:
    - cron: '0 10 * * *'
    
  workflow_dispatch:
    inputs:
      category:
        description: Category
        required: false
        type: string
        default: diapers
      sources:
        description: Sources
        required: false
        type: string
      count:
        description: Count
        required: false
        type: number
      update:
        description: Update
        required: false
        type: boolean
      ignoreErrors:
        description: Ignore Errors
        required: false
        type: boolean
      verbose:
        description: Verbose
        required: false
        type: boolean

jobs:
  scraper:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          repository: Yuen-Affiliates/scraper
          token: ${{ secrets.GH_TOKEN }}

      - name: Run docker image
        uses: ./scraper
        with:
          category: ${{ inputs.category || 'diapers' }}
          count: ${{ inputs.count }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ignoreErrors: ${{ contains(inputs.ignoreErrors, true) }}
          sources: ${{ inputs.sources || 'costco,ebay,target' }}
          update: ${{ contains(inputs.update, true) }}
          verbose: ${{ contains(inputs.verbose, false) }}
